[project]
  name = "ki"
  version = "0.5.0"
  description = "ki shell"
  longDescription = "Extendable Kotlin interactive shell with code completion, syntax highlighting, and other features"
  website = "https://github.com/Kotlin/kotlin-interactive-shell"
  authors = ["Vitaly Khudobakhshov", "Ilya Chernikov"]
  license = "Apache-2"
  java.groupId = "org.jetbrains.kotlinx"
  java.version = "11"

[distributions.ki]
  artifacts = [
    { path = "ki-shell/target/ki-archive.zip" }
  ]
  tags = ["cli", "kotlin", "shell", "interactive"]

[release.github]
  owner = "Kotlin"
  username = "asm0dey"
  skipTag = true
  overwrite = true
  name = "kotlin-interactive-shell"


[packagers.sdkman]
  active = "ALWAYS"
  continueOnError = true
  releaseNotesUrl = "https://github.com/Kotlin/kotlin-interactive-shell/releases/tag/{{tagName}}"
  command = "MAJOR"
